
# html lang
# language: en

# main menu navigation
menu:
  Home: /
  Tags: /tags
  Categories: /categories
  Archives: /archives
  About: /about

# Miscelaneous
favicon: /favicon.ico

# avatar
avatar: /avatar.png

# 侧边栏
# friendlink：友链，设置为 true 的同时在 data 中加入链接和描述
toc:
  enable: true
  friendlink:
    enable: false
    data:
      -
        url: https://github.com/fan-lv
        text: 友链1:这是简介
      - url: https://github.com/fan-lv
        text: 友链2
      - url: https://github.com/fan-lv
        text: 友链3

# Footer Settings
# ---------------
since: 2017

links:
  enable: true
  data:
    -
      url: https://github.com/fan-lv
      text: GitHub
    -
      url: mailto:15757856604@163.com
      text: E-Mail
    -
      url: tencent://message/?uin=1019593584&Site=&Menu=yes
      text: QQ


# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fas fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fas fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fas fa-file-o"></i>
  page_pv_footer:

# stylesheets loaded in the <head>
stylesheets:
- /css/fan.css
- /css/thirdparty/jquery.mCustomScrollbar.min.css

# scripts loaded in the end of the body
scripts:
- /js/thirdparty/jquery-3.3.1.min.js
- /js/thirdparty/velocity.min.js
- /js/thirdparty/jquery.mCustomScrollbar.concat.min.js
- /js/fan.js
- /js/canvas_bg.js
- /js/utils.js
- /js/scroll.js
- /js/sidebar.js
- /js/copy.js

# post 配置
post_meta:
  date_type: updated # created or updated
  categories: true
  tags: true

# recent-posts 中文章内容显示的字数
# 不推荐使用，请尽量在文章中使用 <!-- more --> 来定位要截断的内容
auto_excerpt:
  enable: false
  length: 200

# algolia 搜索
algolia_search:
  enable: false
  hits:
    per_page: 10

# 本地搜索
local_search:
  enable: false

# 复制代码
post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
